name: publish
on:
  push:
    branches:
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: dependencies
        run: |
          sudo apt-get update -qy
          sudo apt-get install -y make
        shell: bash

      - name: checkout
        uses: actions/checkout@v2

      - name: login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: publish
        run: make publish
